### ISSUE TITLE
Where are feedback.js's stylesheets?

### ISSUE THREAD

**Issue by diessica** [filipemerker/feedback.js#1]
GRRR!!!!

**Comment by filipemerker** [comment]
This should be fixed in version 0.1.61

**Comment by diessica** [comment]
DO NOT CLOSE THE ISSUE THEN!! GRRRRRR!!!

**Comment by filipemerker** [comment]
This version is released already. You need to calm down. I'm calling security.

**Comment by diessica** [comment]
WHERE ARE THE STYLESHEETSSSSSS 😭

**Comment by diessica** [comment]
Ok, thank you! :grin:

**Comment by filipemerker** [comment]
`@import "../node_modules/feedback.js/dist/main.css";`
